services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    container_name: admin
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    volumes:
      - ./admin:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      - NODE_ENV=development
    ports:
      - '5174:5174'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - admin
      - frontend
    restart: always
