CREATE DATABASE IF NOT EXISTS Linganore;
USE Linganore;

CREATE TABLE IF NOT EXISTS Events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    isFeatured BOOLEAN DEFAULT FALSE,
    isRecurring BOOLEAN DEFAULT FALSE,
    isArchived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EventDates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    eventID INT NOT NULL,
    date DATE NOT NULL,
    FOREIGN KEY (eventID) REFERENCES Events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EventTimes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    eventDateID INT NOT NULL,
    time TIME NOT NULL,
    FOREIGN KEY (eventDateID) REFERENCES EventDates(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Photos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    eventID INT NOT NULL,
    photoURL VARCHAR(2083) NOT NULL,
    isThumbnail BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (eventID) REFERENCES Events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'viewer') NOT NULL DEFAULT 'viewer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
