FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies and concurrently
RUN npm install && npm install -g nodemon concurrently

COPY . .

EXPOSE 5000

# Run API and scheduler simultaneously
# CMD ["npx", "concurrently", "nodemon index.js", "node scheduler.js"]
# CMD ["sh", "-c", "npx concurrently \"nodemon index.js\" \"node scheduler.js\""]
CMD ["sh", "-c", "npx concurrently --raw \"nodemon index.js\" \"node scheduler.js\""]


